workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic imposter # Name of API key added in Codemagic UI

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      # Add these in Codemagic UI -> App Settings -> Environment variables:
      # - APP_STORE_APP_ID (your App Store Connect App ID)
      vars:
        BUNDLE_ID: "com.rayn100.impostergame"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: production
          include: true

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install EAS CLI
        script: |
          npm install -g eas-cli

      - name: Setup Expo credentials
        script: |
          # Login to Expo (set EXPO_TOKEN in Codemagic environment variables)
          if [ -n "$EXPO_TOKEN" ]; then
            echo "Expo token found, proceeding..."
          else
            echo "Warning: EXPO_TOKEN not set. You may need to set this for EAS builds."
          fi

      - name: Prebuild iOS native project
        script: |
          npx expo prebuild --platform ios --clean

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates

          # Force Manual Signing in the project file (Critical for Expo)
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/ImposterGame.xcodeproj/project.pbxproj

          # Apply profiles
          xcode-project use-profiles --project ios/ImposterGame.xcodeproj

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Increment build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo "0")
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEW_BUILD_NUMBER
          echo "Build number set to: $NEW_BUILD_NUMBER"

      - name: Build iOS app
        script: |
          cd ios
          # Defines the path to the xcarchive
          ARCHIVE_PATH="$PWD/build/ios/xcarchive/ImposterGame.xcarchive"
          EXPORT_OPTIONS_PLIST="$PWD/ExportOptions.plist"

          # Find the provisioning profile UUID
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          if [ -z "$PROFILE_PATH" ]; then
            echo "Error: No provisioning profile found!"
            exit 1
          fi
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          echo "Found Profile UUID: $PROFILE_UUID"

          # 1. Archive the app
          xcodebuild archive \
            -workspace "ImposterGame.xcworkspace" \
            -scheme "ImposterGame" \
            -config Release \
            -archivePath "$ARCHIVE_PATH" \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            DEVELOPMENT_TEAM="Z83Y9VJTKH"

          # 2. Create ExportOptions.plist
          cat > "$EXPORT_OPTIONS_PLIST" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string>Z83Y9VJTKH</string> 
            <key>provisioningProfiles</key>
            <dict>
               <key>$BUNDLE_ID</key>
               <string>$PROFILE_UUID</string>
            </dict>
          </dict>
          </plist>
          EOF

          # Note: We need to dynamically insert Team ID or let it fail? 
          # Better: Let xcodebuild detect or we need to add TEAM_ID var.

          # 3. Export IPA
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$PWD/build/ios/ipa" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST"

    artifacts:
      - ios/build/ios/ipa/*.ipa
      - ios/build/ios/ipa/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"
