workflows:
  android-production-aab:
    name: Android Production AAB
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.rayn100.impostergame"
      node: 18
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'production'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Prebuild Android project
        script: |
          npx expo prebuild --platform android --clean
      - name: Build Android AAB
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - raynusman100hue@gmail.com
        notify:
          success: true
          failure: true

  android-preview-apk:
    name: Android Preview APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.rayn100.impostergame"
      node: 18
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'apk-build'
          include: true
          source: true
        - pattern: 'codemagic'
          include: true
          source: true
        - pattern: 'android-dev'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Prebuild Android project
        script: |
          npx expo prebuild --platform android --clean
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - raynusman100hue@gmail.com
        notify:
          success: true
          failure: true
