workflows:
  android-preview:
    name: Android Preview Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform android --no-interactive
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/**/*.apk
