workflows:
  android-preview:
    name: Android Preview Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform ios
      - name: Install CocoaPods
        script: cd ios && pod install
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "com.rayn100.impostergame" --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up code signing settings
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "ios/ImposterGame.xcworkspace" --scheme "ImposterGame"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - *.dSYM.zip
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
