import { StyleSheet, Platform } from 'react-native';

export const getStyles = (theme) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'ios' ? 50 : 35,
        paddingBottom: 20,
        flexGrow: 1,
    },
    fixedContent: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'ios' ? 50 : 35,
        paddingBottom: 20,
    },
    // Header
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.primary + '30',
    },
    backBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: theme.colors.primary + '50',
    },
    backText: {
        color: theme.colors.primary,
        fontSize: 26,
        fontFamily: 'CabinetGrotesk-Black',
        marginTop: -2,
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
    },
    kodakBadge: {
        backgroundColor: theme.colors.primary,
        paddingHorizontal: 16,
        paddingVertical: 5,
        borderRadius: 4,
    },
    kodakBadgeText: {
        color: theme.colors.secondary,
        fontSize: 12,
        fontFamily: 'Panchang-Bold',
        letterSpacing: 3,
    },
    // Film Frame Card
    filmFrame: {
        backgroundColor: theme.colors.surface,
        borderRadius: 12,
        padding: 18,
        borderWidth: 2,
        borderColor: theme.colors.primary + '40',
    },
    frameTitle: {
        fontSize: 15,
        fontFamily: 'Panchang-Bold',
        color: theme.colors.text,
        textAlign: 'center',
        letterSpacing: 2,
        marginBottom: 14,
    },
    // Input styles
    inputGroup: {
        marginBottom: 10,
    },
    inputLabel: {
        color: theme.colors.primary,
        fontSize: 10,
        fontFamily: 'Panchang-Bold',
        letterSpacing: 2,
        marginBottom: 5,
        marginLeft: 4,
    },
    input: {
        backgroundColor: theme.colors.background,
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 14,
        color: theme.colors.text,
        fontFamily: 'Teko-Medium',
        fontSize: 18,
        borderWidth: 1,
        borderColor: theme.colors.textMuted + '50',
    },
    inputCentered: {
        textAlign: 'center',
        fontSize: 22,
        letterSpacing: 2,
    },
    forgotBtn: {
        alignSelf: 'flex-end',
        marginBottom: 12,
        marginTop: -4,
    },
    forgotText: {
        color: theme.colors.primary,
        fontSize: 11,
        fontFamily: 'Teko-Medium',
        letterSpacing: 1,
    },
    divider: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 14,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: theme.colors.textMuted + '40',
    },
    dividerText: {
        color: theme.colors.textMuted,
        fontSize: 11,
        fontFamily: 'Teko-Medium',
        marginHorizontal: 12,
        letterSpacing: 2,
    },
    switchText: {
        color: theme.colors.textSecondary,
        fontSize: 13,
        fontFamily: 'Teko-Medium',
        textAlign: 'center',
        letterSpacing: 1,
    },
    infoText: {
        color: theme.colors.textSecondary,
        fontSize: 14,
        fontFamily: 'Teko-Medium',
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 8,
    },
    // Avatar Omnitrix Selector
    sectionLabel: {
        color: theme.colors.primary,
        fontSize: 10,
        fontFamily: 'Panchang-Bold',
        letterSpacing: 2,
        textAlign: 'center',
        marginBottom: 6,
    },
    avatarToggle: {
        flexDirection: 'row',
        backgroundColor: theme.colors.background,
        borderRadius: 25,
        padding: 4,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: theme.colors.primary + '30',
    },
    toggleBtn: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 22,
        alignItems: 'center',
    },
    toggleText: {
        fontSize: 11,
        fontFamily: 'CabinetGrotesk-Black',
        letterSpacing: 1,
    },
    customAvatarSection: {
        alignItems: 'center',
        marginBottom: 14,
    },
    customAvatarPreview: {
        marginVertical: 12,
    },
    emptyAvatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 3,
        borderStyle: 'dashed',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.background,
    },
    editAvatarBtn: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 2,
    },
    editAvatarText: {
        fontSize: 12,
        fontFamily: 'CabinetGrotesk-Bold',
        letterSpacing: 1,
    },
    omnitrixContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 14,
    },
    avatarFilmStrip: {
        backgroundColor: theme.colors.background,
        borderRadius: 8,
        paddingVertical: 8,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: theme.colors.primary + '30',
    },
    avatarScrollContent: {
        paddingHorizontal: 8,
        gap: 8,
    },
    avatarFrame: {
        backgroundColor: theme.colors.surface,
        borderRadius: 8,
        padding: 6,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'transparent',
        position: 'relative',
    },
    avatarFrameSelected: {
        borderColor: theme.colors.primary,
        backgroundColor: theme.colors.primary + '15',
    },
    avatarSprocket: {
        width: 40,
        height: 4,
        backgroundColor: theme.colors.textMuted + '30',
        borderRadius: 2,
        marginVertical: 3,
    },
    selectedBadge: {
        position: 'absolute',
        top: -6,
        right: -6,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectedBadgeText: {
        color: theme.colors.secondary,
        fontSize: 12,
    },
    // Preview
    previewSection: {
        alignItems: 'center',
        marginBottom: 16,
    },
    previewFrame: {
        padding: 8,
        borderRadius: 50,
        borderWidth: 3,
        borderColor: theme.colors.primary,
        backgroundColor: theme.colors.background,
    },
    // Footer
    footer: {
        alignItems: 'center',
        marginTop: 16,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: theme.colors.primary + '20',
    },
    footerText: {
        color: theme.colors.textMuted,
        fontSize: 9,
        fontFamily: 'Teko-Medium',
        letterSpacing: 3,
        opacity: 0.6,
    },
    // Delete Account Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        width: '100%',
        maxWidth: 340,
        borderRadius: 16,
        padding: 24,
        borderWidth: 2,
        borderColor: theme.colors.error + '50',
    },
    modalTitle: {
        fontSize: 16,
        fontFamily: 'Panchang-Bold',
        textAlign: 'center',
        marginBottom: 12,
        letterSpacing: 2,
    },
    modalText: {
        fontSize: 14,
        fontFamily: 'Teko-Medium',
        textAlign: 'center',
        lineHeight: 20,
    },
});
