/**
 * Dictionary of words categorized for the game.
 * Translations are handled automatically by the API.
 */
export const wordCategories = {
    general: [
        { word: 'Pizza', hint: 'A popular Italian dish' },
        { word: 'Guitar', hint: 'A string instrument' },
        { word: 'Bicycle', hint: 'Two-wheeled transport' },
        { word: 'Sun', hint: 'Star at the center of our system' },
        { word: 'Water', hint: 'Essential for life' },
        { word: 'Clock', hint: 'Tells time' },
        { word: 'Book', hint: 'Pages with stories' },
        { word: 'Doctor', hint: 'Treats patients' },
        { word: 'Fire', hint: 'Hot and burning' },
        { word: 'Tree', hint: 'Has leaves and a trunk' },
        { word: 'Computer', hint: 'Electronic machine' },
        { word: 'Music', hint: 'Sound and rhythm' },
        { word: 'Money', hint: 'Used to buy things' },
        { word: 'Sleep', hint: 'Rest at night' },
        { word: 'Dream', hint: 'Thoughts while sleeping' },
        { word: 'Happy', hint: 'Feeling of joy' },
        { word: 'Crying', hint: 'Tears falling' },
        { word: 'Friend', hint: 'A person you like' },
        { word: 'Family', hint: 'Parents and children' },
        { word: 'House', hint: 'Place to live' },
        { word: 'Love', hint: 'Deep affection' },
        { word: 'Time', hint: 'Measured in seconds' },
        { word: 'Work', hint: 'Job or task' },
        { word: 'Idea', hint: 'A thought or suggestion' },
        { word: 'Light', hint: 'Opposite of dark' },
        { word: 'Rain', hint: 'Water from clouds' },
        { word: 'Snow', hint: 'Frozen precipitation' },
        { word: 'Wind', hint: 'Moving air' },
        { word: 'Thunder', hint: 'Loud sky sound' },
        { word: 'Cloud', hint: 'White fluffy formation' },
        { word: 'Night', hint: 'Dark time' },
        { word: 'Day', hint: 'Light time' },
        { word: 'Sea', hint: 'Large body of water' },
        { word: 'Ocean', hint: 'Massive sea' },
        { word: 'Mountain', hint: 'Very tall landform' },
        { word: 'River', hint: 'Flowing water' },
    ],
    places: [
        { word: 'Paris', hint: 'City of Lights' },
        { word: 'School', hint: 'Place for learning' },
        { word: 'Beach', hint: 'Sand and sea' },
        { word: 'Library', hint: 'Quiet place with books' },
        { word: 'Hospital', hint: 'Place for the sick' },
        { word: 'Moon', hint: 'Earth\'s natural satellite' },
        { word: 'Mars', hint: 'The Red Planet' },
        { word: 'Airport', hint: 'Planes land here' },
        { word: 'London', hint: 'Capital of England' },
        { word: 'Tokyo', hint: 'Capital of Japan' },
        { word: 'New York', hint: 'The Big Apple' },
        { word: 'Dubai', hint: 'City of skyscrapers' },
        { word: 'Egypt', hint: 'Land of Pyramids' },
        { word: 'Mount Everest', hint: 'Highest mountain' },
        { word: 'Antarctica', hint: 'Frozen continent' },
        { word: 'Cinema', hint: 'Watch movies here' },
        { word: 'Park', hint: 'Green space in city' },
        { word: 'Gym', hint: 'Place to exercise' },
        { word: 'Restaurant', hint: 'Place to eat out' },
        { word: 'Hotel', hint: 'Stay for a night' },
        { word: 'Stadium', hint: 'Sports arena' },
        { word: 'Museum', hint: 'History and art' },
        { word: 'Zoo', hint: 'See wild animals' },
        { word: 'Space Station', hint: 'Orbiting lab' },
        { word: 'Forest', hint: 'Many trees' },
        { word: 'Desert', hint: 'Hot sandy place' },
        { word: 'Ocean', hint: 'Biggest water body' },
        { word: 'Island', hint: 'Land surrounded by water' },
        { word: 'Mountain', hint: 'High elevation' },
        { word: 'Cave', hint: 'Underground hollow' },
        { word: 'Waterfall', hint: 'Cascading water' },
        { word: 'Lake', hint: 'Inland water body' },
    ],
    food: [
        { word: 'Apple', hint: 'A red or green fruit' },
        { word: 'Sushi', hint: 'Japanese rice dish' },
        { word: 'Burger', hint: 'Sandwich with a patty' },
        { word: 'Ice Cream', hint: 'Frozen dessert' },
        { word: 'Coffee', hint: 'Caffeinated morning drink' },
        { word: 'Chocolate', hint: 'Sweet treat from cocoa' },
        { word: 'Pasta', hint: 'Italian noodle dish' },
        { word: 'Steak', hint: 'Grilled beef' },
        { word: 'Salad', hint: 'Bowl of vegetables' },
        { word: 'Bread', hint: 'Baked dough' },
        { word: 'Cheese', hint: 'Dairy product' },
        { word: 'Chicken', hint: 'Common poultry' },
        { word: 'Egg', hint: 'Laid by hens' },
        { word: 'Banana', hint: 'Yellow curved fruit' },
        { word: 'Orange', hint: 'Citrus fruit' },
        { word: 'Grape', hint: 'Small round fruit' },
        { word: 'Strawberry', hint: 'Red berry' },
        { word: 'Potato', hint: 'Starch tuber' },
        { word: 'Tomato', hint: 'Red vegetable/fruit' },
        { word: 'Onion', hint: 'Makes you cry' },
        { word: 'Garlic', hint: 'Vampires hate it' },
        { word: 'Rice', hint: 'Small white grains' },
        { word: 'Tea', hint: 'Hot leaf drink' },
        { word: 'Juice', hint: 'Liquid from fruit' },
        { word: 'Sandwich', hint: 'Bread with filling' },
        { word: 'Waffle', hint: 'Grid breakfast' },
        { word: 'Pancake', hint: 'Flat breakfast cake' },
        { word: 'Donut', hint: 'Ring-shaped sweet' },
        { word: 'Cake', hint: 'Birthday dessert' },
        { word: 'Cookie', hint: 'Baked sweet snack' },
        { word: 'Pie', hint: 'Filled pastry' },
        { word: 'Soup', hint: 'Hot liquid dish' },
        { word: 'Noodles', hint: 'Long thin pasta' },
        { word: 'Pickle', hint: 'Sour preserved' },
    ],
    entertainment: [
        { word: 'Movie', hint: 'Film on a screen' },
        { word: 'Circus', hint: 'Show with clowns' },
        { word: 'Batman', hint: 'The Dark Knight' },
        { word: 'Harry Potter', hint: 'The Boy Who Lived' },
        { word: 'YouTube', hint: 'Video sharing platform' },
        { word: 'Minecraft', hint: 'Block building game' },
        { word: 'Netflix', hint: 'Streaming service' },
        { word: 'Spiderman', hint: 'Web slinger' },
        { word: 'Iron Man', hint: 'Tony Stark' },
        { word: 'Superman', hint: 'Man of Steel' },
        { word: 'Barbie', hint: 'Famous doll' },
        { word: 'Anime', hint: 'Japanese animation' },
        { word: 'Bollywood', hint: 'Indian film industry' },
        { word: 'Hollywood', hint: 'US film industry' },
        { word: 'TikTok', hint: 'Short video app' },
        { word: 'Instagram', hint: 'Photo sharing app' },
        { word: 'Fortnite', hint: 'Battle royale game' },
        { word: 'Mario', hint: 'Italian plumber' },
        { word: 'Pikachu', hint: 'Electric mouse' },
        { word: 'Chess', hint: 'Board game of strategy' },
        { word: 'Poker', hint: 'Card game' },
        { word: 'Concert', hint: 'Live music show' },
        { word: 'Magic', hint: 'Tricks and illusions' },
        { word: 'Dance', hint: 'Move to music' },
        { word: 'Opera', hint: 'Theatrical singing' },
        { word: 'Disney', hint: 'Famous animation studio' },
        { word: 'Avatar', hint: 'Blue aliens movie' },
        { word: 'Titanic', hint: 'Sinking ship movie' },
        { word: 'Marvel', hint: 'Superhero universe' },
        { word: 'Star Wars', hint: 'Space saga' },
        { word: 'Game of Thrones', hint: 'Fantasy TV series' },
        { word: 'Friends', hint: 'Classic sitcom' },
    ],
    objects: [
        { word: 'Chair', hint: 'You sit on it' },
        { word: 'Phone', hint: 'Used for calling' },
        { word: 'Shoe', hint: 'Worn on feet' },
        { word: 'Key', hint: 'Unlocks doors' },
        { word: 'Table', hint: 'Furniture with legs' },
        { word: 'Car', hint: 'Road vehicle' },
        { word: 'Pen', hint: 'Writes with ink' },
        { word: 'Paper', hint: 'Write on this' },
        { word: 'Bag', hint: 'Carry things in it' },
        { word: 'Watch', hint: 'Wear on wrist' },
        { word: 'Glasses', hint: 'Helps vision' },
        { word: 'Hat', hint: 'Worn on head' },
        { word: 'Umbrella', hint: 'Protect from rain' },
        { word: 'Bottle', hint: 'Holds liquid' },
        { word: 'Knife', hint: 'Used to cut' },
        { word: 'Spoon', hint: 'Used to eat soup' },
        { word: 'Fork', hint: 'Used to pierce food' },
        { word: 'Plate', hint: 'Eat off this' },
        { word: 'Cup', hint: 'Drink from this' },
        { word: 'Bed', hint: 'Sleep on this' },
        { word: 'Laptop', hint: 'Portable PC' },
        { word: 'Camera', hint: 'Takes photos' },
        { word: 'Mirror', hint: 'Reflects image' },
        { word: 'Soap', hint: 'Cleans body' },
        { word: 'Towel', hint: 'Dries you off' },
        { word: 'Comb', hint: 'Styles hair' },
        { word: 'Scissors', hint: 'Cutting tool' },
        { word: 'Needle', hint: 'Sewing tool' },
        { word: 'Thread', hint: 'For sewing' },
        { word: 'Button', hint: 'Fastens clothes' },
        { word: 'Zipper', hint: 'Quick fastener' },
        { word: 'Wallet', hint: 'Holds money' },
        { word: 'Backpack', hint: 'Carries books' },
    ],
    trends: [
        { word: 'AI', hint: 'Artificial Intelligence' },
        { word: 'Crypto', hint: 'Digital currency' },
        { word: 'Influencer', hint: 'Famous on social media' },
        { word: 'Streaming', hint: 'Live broadcasting' },
        { word: 'Meme', hint: 'Funny internet picture' },
        { word: 'Viral', hint: 'Spreads fast online' },
        { word: 'Selfie', hint: 'Photo of yourself' },
        { word: 'Hashtag', hint: 'Used on Twitter/Insta' },
        { word: 'Podcast', hint: 'Audio show' },
        { word: 'Vlog', hint: 'Video blog' },
        { word: 'NFT', hint: 'Digital collectible' },
        { word: 'Metaverse', hint: 'Virtual world' },
        { word: 'Remote Work', hint: 'Working from home' },
        { word: 'Drone', hint: 'Flying robot' },
        { word: 'Electric Car', hint: 'Tesla' },
        { word: 'Smartwatch', hint: 'Wearable tech' },
        { word: 'Filter', hint: 'Changes photo look' },
        { word: 'Reel', hint: 'Short Instagram video' },
        { word: 'Challenge', hint: 'Trending task' },
        { word: 'Algorithm', hint: 'Controls feed' },
        { word: 'Troll', hint: 'Internet pest' },
        { word: 'Bot', hint: 'Automated account' },
        { word: 'App', hint: 'Software on phone' },
        { word: 'Cloud', hint: 'Online storage' },
        { word: 'Wi-Fi', hint: 'Wireless internet' },
        { word: 'Emoji', hint: 'Digital emotion icons' },
        { word: 'GIF', hint: 'Moving image' },
        { word: 'Screenshot', hint: 'Capture phone screen' },
        { word: 'Notification', hint: 'Phone alert' },
        { word: 'Download', hint: 'Get from internet' },
        { word: 'Upload', hint: 'Send to internet' },
        { word: 'Password', hint: 'Login security' },
    ],
    sport: [
        { word: 'Soccer', hint: 'Football (World)' },
        { word: 'Basketball', hint: 'Hoops and dunking' },
        { word: 'Cricket', hint: 'Bat and ball' },
        { word: 'Tennis', hint: 'Racket and yellow ball' },
        { word: 'Golf', hint: 'Clubs and holes' },
        { word: 'Volleyball', hint: 'Net and spike' },
        { word: 'Swimming', hint: 'Water racing' },
        { word: 'Boxing', hint: 'Fighting with gloves' },
        { word: 'Running', hint: 'Track usually' },
        { word: 'Yoga', hint: 'Stretching poses' },
        { word: 'Gymnastics', hint: 'Flips and balance' },
        { word: 'Skiing', hint: 'Snow sliding' },
        { word: 'Surfing', hint: 'Riding waves' },
        { word: 'Skating', hint: 'Ice or wheels' },
        { word: 'Hockey', hint: 'Puck and stick' },
        { word: 'Rugby', hint: 'Oval ball contact' },
        { word: 'Baseball', hint: 'Bat and diamond' },
        { word: 'Badminton', hint: 'Shuttlecock' },
        { word: 'Table Tennis', hint: 'Ping pong' },
        { word: 'Cycling', hint: 'Bike racing' },
        { word: 'Wrestling', hint: 'Grappling' },
        { word: 'Karate', hint: 'Martial art' },
        { word: 'Marathon', hint: 'Long race' },
        { word: 'Sprinting', hint: 'Fast race' },
        { word: 'Medal', hint: 'Gold, Silver, Bronze' },
        { word: 'Trophy', hint: 'Winner prize' },
        { word: 'Stadium', hint: 'Sports venue' },
        { word: 'Coach', hint: 'Team trainer' },
        { word: 'Referee', hint: 'Game judge' },
        { word: 'Whistle', hint: 'Referee tool' },
        { word: 'Goal', hint: 'Score point' },
        { word: 'Team', hint: 'Group of players' },
    ],
    dailyLife: [
        { word: 'Traffic', hint: 'Cars on road' },
        { word: 'Shopping', hint: 'Buying things' },
        { word: 'Cooking', hint: 'Making food' },
        { word: 'Cleaning', hint: 'Tidying up' },
        { word: 'Meeting', hint: 'Gathering at work' },
        { word: 'Email', hint: 'Digital letter' },
        { word: 'Salary', hint: 'Pay for work' },
        { word: 'Rent', hint: 'Pay for house' },
        { word: 'Bus', hint: 'Public transport' },
        { word: 'Train', hint: 'Rail transport' },
        { word: 'Alarm', hint: 'Wakes you up' },
        { word: 'Breakfast', hint: 'Morning meal' },
        { word: 'Lunch', hint: 'Midday meal' },
        { word: 'Dinner', hint: 'Evening meal' },
        { word: 'Shower', hint: 'Bathing' },
        { word: 'Walking', hint: 'Moving on legs' },
        { word: 'Sleeping', hint: 'Resting eyes' },
        { word: 'Talking', hint: 'Speaking' },
        { word: 'Listening', hint: 'Hearing' },
        { word: 'Reading', hint: 'Looking at text' },
        { word: 'Writing', hint: 'Pen on paper' },
        { word: 'Drawing', hint: 'Creating art' },
        { word: 'Party', hint: 'Celebration' },
        { word: 'Wedding', hint: 'Marriage ceremony' },
        { word: 'Birthday', hint: 'Age celebration' },
        { word: 'Holiday', hint: 'Day off' },
        { word: 'Vacation', hint: 'Long break' },
        { word: 'Weekend', hint: 'Saturday Sunday' },
        { word: 'Morning', hint: 'Early day' },
        { word: 'Evening', hint: 'Late day' },
        { word: 'Midnight', hint: '12 AM' },
        { word: 'Noon', hint: '12 PM' },
    ],
    things: [
        { word: 'Box', hint: 'Container' },
        { word: 'Ball', hint: 'Round object' },
        { word: 'Ring', hint: 'Worn on finger' },
        { word: 'Chain', hint: 'Linked metal' },
        { word: 'Lock', hint: 'Secures things' },
        { word: 'Key', hint: 'Opens lock' },
        { word: 'Door', hint: 'Entryway' },
        { word: 'Window', hint: 'Look through it' },
        { word: 'Wall', hint: 'Brick divider' },
        { word: 'Floor', hint: 'Stand on it' },
        { word: 'Roof', hint: 'Top of house' },
        { word: 'Fan', hint: 'Moves air' },
        { word: 'Lamp', hint: 'Gives light' },
        { word: 'Candle', hint: 'Wax light' },
        { word: 'Soap', hint: 'Cleaning bar' },
        { word: 'Toothbrush', hint: 'Cleans teeth' },
        { word: 'Pillow', hint: 'Head rest' },
        { word: 'Blanket', hint: 'Keeps warm' },
        { word: 'Curtain', hint: 'Covers window' },
        { word: 'Carpet', hint: 'Floor rug' },
        { word: 'Vase', hint: 'Holds flowers' },
        { word: 'Pot', hint: 'Cooking vessel' },
        { word: 'Pan', hint: 'Frying vessel' },
        { word: 'Ladder', hint: 'Climb up' },
        { word: 'Hammer', hint: 'Hits nails' },
        { word: 'Screw', hint: 'Threaded fastener' },
        { word: 'Nail', hint: 'Metal pin' },
        { word: 'Drill', hint: 'Makes holes' },
        { word: 'Paint', hint: 'Colors walls' },
        { word: 'Brush', hint: 'Applies paint' },
        { word: 'Rope', hint: 'Thick string' },
        { word: 'Tape', hint: 'Sticky strip' },
    ],
    science: [
        { word: 'Atom', hint: 'Basic unit of matter' },
        { word: 'Gravity', hint: 'Keeps us on ground' },
        { word: 'Galaxy', hint: 'Collection of stars' },
        { word: 'DNA', hint: 'Genetic code' },
        { word: 'Robot', hint: 'Mechanical helper' },
        { word: 'Virus', hint: 'Microscopic agent' },
        { word: 'Laser', hint: 'Focused light beam' },
        { word: 'Magnet', hint: 'Attracts iron' },
        { word: 'Fossil', hint: 'Old bone in rock' },
        { word: 'Volcano', hint: 'Erupts with lava' },
        { word: 'Planet', hint: 'Orbits a star' },
        { word: 'Telescope', hint: 'See far away' },
        { word: 'Microscope', hint: 'See tiny things' },
        { word: 'Battery', hint: 'Stores energy' },
        { word: 'Satellite', hint: 'Orbits Earth' },
        { word: 'Rocket', hint: 'Goes to space' },
        { word: 'Astronaut', hint: 'Space traveler' },
        { word: 'Laboratory', hint: 'Science work place' },
        { word: 'Chemical', hint: 'Reactive substance' },
        { word: 'Beaker', hint: 'Glass container' },
        { word: 'Formula', hint: 'Math recipe' },
        { word: 'Experiment', hint: 'Scientific test' },
        { word: 'Evolution', hint: 'Change over time' },
        { word: 'Black Hole', hint: 'Light cannot escape' },
        { word: 'Meteor', hint: 'Falling star' },
    ],
    history: [
        { word: 'Pyramid', hint: 'Egyptian tomb' },
        { word: 'Knight', hint: 'Medieval warrior' },
        { word: 'Castle', hint: 'Fortified home' },
        { word: 'Viking', hint: 'Norse seafarer' },
        { word: 'Samurai', hint: 'Japanese warrior' },
        { word: 'Gladiator', hint: 'Roman fighter' },
        { word: 'Pharaoh', hint: 'Egyptian king' },
        { word: 'Mummy', hint: 'Wrapped body' },
        { word: 'Sword', hint: 'Sharp weapon' },
        { word: 'Shield', hint: 'Protection tool' },
        { word: 'Crown', hint: 'Royal hat' },
        { word: 'Throne', hint: 'Royal chair' },
        { word: 'Empire', hint: 'Large kingdom' },
        { word: 'War', hint: 'Large conflict' },
        { word: 'Peace', hint: 'No fighting' },
        { word: 'Revolution', hint: 'Big change' },
        { word: 'Discovery', hint: 'Finding new lands' },
        { word: 'Ancient', hint: 'Very old' },
        { word: 'Coin', hint: 'Metal money' },
        { word: 'Map', hint: 'Guide to places' },
    ],
    mythology: [
        { word: 'Dragon', hint: 'Fire breathing lizard' },
        { word: 'Unicorn', hint: 'Horse with horn' },
        { word: 'Mermaid', hint: 'Fish woman' },
        { word: 'Zeus', hint: 'Greek god of sky' },
        { word: 'Thor', hint: 'Norse god of thunder' },
        { word: 'Hercules', hint: 'Strong hero' },
        { word: 'Phoenix', hint: 'Fire bird' },
        { word: 'Ghost', hint: 'Spirit' },
        { word: 'Vampire', hint: 'Drinks blood' },
        { word: 'Werewolf', hint: 'Wolf man' },
        { word: 'Wizard', hint: 'User of magic' },
        { word: 'Witch', hint: 'Magic woman' },
        { word: 'Fairy', hint: 'Small magical flyer' },
        { word: 'Elf', hint: 'Pointy eared' },
        { word: 'Giant', hint: 'Very big person' },
        { word: 'Angel', hint: 'Divine being' },
        { word: 'Demon', hint: 'Evil spirit' },
        { word: 'Medusa', hint: 'Snake hair' },
        { word: 'Poseidon', hint: 'God of sea' },
        { word: 'Hades', hint: 'God of underword' },
    ],
    nature: [
        { word: 'Flower', hint: 'Colorful plant part' },
        { word: 'Grass', hint: 'Green ground cover' },
        { word: 'Cactus', hint: 'Spiky desert plant' },
        { word: 'Rose', hint: 'Love flower' },
        { word: 'Sunflower', hint: 'Follows the sun' },
        { word: 'Palm Tree', hint: 'Tropical tree' },
        { word: 'Leaf', hint: 'On a branch' },
        { word: 'Root', hint: 'Underground plant part' },
        { word: 'Seed', hint: 'Starts a plant' },
        { word: 'Soil', hint: 'Dirt for plants' },
        { word: 'Mushroom', hint: 'Fungi' },
        { word: 'Bamboo', hint: 'Panda food' },
        { word: 'Vine', hint: 'Climbing plant' },
        { word: 'Forest', hint: 'Many trees' },
        { word: 'Jungle', hint: 'Thick forest' },
        { word: 'River', hint: 'Flowing water' },
        { word: 'Ocean', hint: 'Salty water' },
        { word: 'Desert', hint: 'Dry sandy place' },
        { word: 'Mountain', hint: 'High rock' },
        { word: 'Valley', hint: 'Low land' },
        { word: 'Canyon', hint: 'Deep gorge' },
        { word: 'Cliff', hint: 'Steep drop' },
        { word: 'Cave', hint: 'Dark hole in rock' },
        { word: 'Beach', hint: 'Sand by sea' },
        { word: 'Island', hint: 'Surrounded by water' },
        { word: 'Volcano', hint: 'Erupts lava' },
        { word: 'Rainforest', hint: 'Wet jungle' },
        { word: 'Swamp', hint: 'Wet muddy land' },
        { word: 'Lake', hint: 'Inland water' },
        { word: 'Pond', hint: 'Small lake' },
    ],
    tech: [
        { word: 'Robot', hint: 'Automated machine' },
        { word: 'Computer', hint: 'Think machine' },
        { word: 'Internet', hint: 'World wide web' },
        { word: 'Software', hint: 'Code programs' },
        { word: 'Hardware', hint: 'Physical parts' },
        { word: 'Keyboard', hint: 'Typing tool' },
        { word: 'Mouse', hint: 'Clicking tool' },
        { word: 'Screen', hint: 'Display' },
        { word: 'Battery', hint: 'Power cell' },
        { word: 'Charger', hint: 'Refills battery' },
        { word: 'Cable', hint: 'Wire connector' },
        { word: 'Wifi', hint: 'Wireless net' },
        { word: 'Bluetooth', hint: 'Short range wireless' },
        { word: 'Server', hint: 'Hosts data' },
        { word: 'Cloud', hint: 'Remote storage' },
        { word: 'Database', hint: 'Stores info' },
        { word: 'Pixel', hint: 'Dot on screen' },
        { word: 'Bug', hint: 'Error in code' },
        { word: 'Hacker', hint: 'Breaks security' },
        { word: 'Virus', hint: 'Malware' },
        { word: 'Firewall', hint: 'Network protection' },
        { word: 'Encryption', hint: 'Secret code' },
        { word: 'Password', hint: 'Secret key' },
        { word: 'Email', hint: 'Digital mail' },
        { word: 'Chat', hint: 'Online talk' },
        { word: 'Video Game', hint: 'Digital play' },
        { word: 'Console', hint: 'Gaming box' },
        { word: 'Controller', hint: 'Game input' },
        { word: 'Headphones', hint: 'Ear speakers' },
        { word: 'Microphone', hint: 'Voice input' },
    ],
    fashion: [
        { word: 'Dress', hint: 'One piece cloth' },
        { word: 'Skirt', hint: 'Lower body cloth' },
        { word: 'Shirt', hint: 'Upper body cloth' },
        { word: 'Pants', hint: 'Leg covering' },
        { word: 'Jeans', hint: 'Denim pants' },
        { word: 'Jacket', hint: 'Outer wear' },
        { word: 'Coat', hint: 'Warm outer wear' },
        { word: 'Hat', hint: 'Head wear' },
        { word: 'Cap', hint: 'Casual hat' },
        { word: 'Scarf', hint: 'Neck warmer' },
        { word: 'Gloves', hint: 'Hand warmers' },
        { word: 'Socks', hint: 'Foot covers' },
        { word: 'Shoes', hint: 'Foot wear' },
        { word: 'Boots', hint: 'High shoes' },
        { word: 'Heels', hint: 'Tall shoes' },
        { word: 'Sneakers', hint: 'Sport shoes' },
        { word: 'Belt', hint: 'Holds pants' },
        { word: 'Tie', hint: 'Formal neck wear' },
        { word: 'Suit', hint: 'Formal set' },
        { word: 'Watch', hint: 'Wrist time' },
        { word: 'Ring', hint: 'Finger jewelry' },
        { word: 'Necklace', hint: 'Neck jewelry' },
        { word: 'Earring', hint: 'Ear jewelry' },
        { word: 'Bracelet', hint: 'Wrist jewelry' },
        { word: 'Purse', hint: 'Hand bag' },
        { word: 'Wallet', hint: 'Money holder' },
        { word: 'Glasses', hint: 'Eye aid' },
        { word: 'Sunglasses', hint: 'Dark glasses' },
        { word: 'Makeup', hint: 'Face paint' },
        { word: 'Perfume', hint: 'Nice smell' },
    ]
};

/**
 * UI Translation mapping for static UI elements.
 */
export const UI_TRANSLATIONS = {
    en: {
        citizen: 'CITIZEN',
        impostor: 'IMPOSTOR',
        secretWord: 'Secret Word',
        hint: 'Hint',
    },
    // Add other languages here if you want STATIC UI translation support
    // But dynamic content (words) will use the API.
};

/**
 * Get a random word and hint from specific categories or mixed.
 * @param {string|Array<string>} categoryKeys - The key(s) of the category.
 * @returns {Object} { word, hint }
 */

// Track recently used words to avoid immediate repeats
let recentlyUsedWords = [];
const MAX_RECENT_WORDS = 20; // Remember last 20 words

export function getRandomWord(categoryKeys = ['all']) {
    let availableWords = [];
    const keys = Array.isArray(categoryKeys) ? categoryKeys : [categoryKeys];

    // Helper to add category to word objects
    const addCategory = (list, cat) => list.map(w => ({ ...w, category: cat }));

    if (keys.includes('all') || keys.length === 0) {
        Object.keys(wordCategories).forEach(key => {
            availableWords = [...availableWords, ...addCategory(wordCategories[key], key)];
        });
    } else {
        keys.forEach(key => {
            if (wordCategories[key]) {
                availableWords = [...availableWords, ...addCategory(wordCategories[key], key)];
            }
        });
    }

    // Fallback
    if (availableWords.length === 0) {
        availableWords = addCategory(wordCategories.general, 'general');
    }

    // Filter out recently used words if we have enough options
    let filteredWords = availableWords.filter(w => !recentlyUsedWords.includes(w.word));

    // If we've exhausted all words, reset the recent list
    if (filteredWords.length === 0) {
        recentlyUsedWords = [];
        filteredWords = availableWords;
    }

    // Pick random word from filtered list
    const randomIndex = Math.floor(Math.random() * filteredWords.length);
    const selectedWord = filteredWords[randomIndex];

    // Track this word as recently used
    recentlyUsedWords.push(selectedWord.word);
    if (recentlyUsedWords.length > MAX_RECENT_WORDS) {
        recentlyUsedWords.shift(); // Remove oldest
    }

    return selectedWord;
}

export const CATEGORY_LABELS = [
    { key: 'all', label: 'Random (All)' },
    { key: 'general', label: 'General' },
    { key: 'entertainment', label: 'Entertainment' },
    { key: 'places', label: 'Places' },
    { key: 'food', label: 'Food' },
    { key: 'objects', label: 'Objects' },
    { key: 'trends', label: 'Trends' },
    { key: 'sport', label: 'Sports' },
    { key: 'dailyLife', label: 'Daily Life' },
    { key: 'things', label: 'Things' },
    { key: 'science', label: 'Science' },
    { key: 'history', label: 'History' },
    { key: 'mythology', label: 'Mythology' },
    { key: 'nature', label: 'Nature' },
    { key: 'tech', label: 'Technology' },
    { key: 'fashion', label: 'Fashion' },
];
