/**
 * Dictionary of words categorized for the game.
 * Translations are handled automatically by the API.
 */
export const wordCategories = {
    places: [
        { word: 'Paris', hint: 'City of Lights' },
        { word: 'School', hint: 'Place for learning' },
        { word: 'Beach', hint: 'Sand and sea' },
        { word: 'Library', hint: 'Quiet place with books' },
        { word: 'Hospital', hint: 'Place for the sick' },
        { word: 'Moon', hint: 'Earth\'s natural satellite' },
        { word: 'Mars', hint: 'The Red Planet' },
        { word: 'Airport', hint: 'Planes land here' },
        { word: 'London', hint: 'Capital of England' },
        { word: 'Tokyo', hint: 'Capital of Japan' },
        { word: 'New York', hint: 'The Big Apple' },
        { word: 'Dubai', hint: 'City of skyscrapers' },
        { word: 'Egypt', hint: 'Land of Pyramids' },
        { word: 'Mount Everest', hint: 'Highest mountain' },
        { word: 'Antarctica', hint: 'Frozen continent' },
        { word: 'Cinema', hint: 'Watch movies here' },
        { word: 'Park', hint: 'Green space in city' },
        { word: 'Gym', hint: 'Place to exercise' },
        { word: 'Restaurant', hint: 'Place to eat out' },
        { word: 'Hotel', hint: 'Stay for a night' },
        { word: 'Stadium', hint: 'Sports arena' },
        { word: 'Museum', hint: 'History and art' },
        { word: 'Zoo', hint: 'See wild animals' },
        { word: 'Space Station', hint: 'Orbiting lab' },
        { word: 'Forest', hint: 'Many trees' },
        { word: 'Desert', hint: 'Hot sandy place' },
        { word: 'Ocean', hint: 'Biggest water body' },
        { word: 'Island', hint: 'Land surrounded by water' },
        { word: 'Mountain', hint: 'High elevation' },
        { word: 'Cave', hint: 'Underground hollow' },
        { word: 'Waterfall', hint: 'Cascading water' },
        { word: 'Lake', hint: 'Inland water body' },
    ],
    food: [
        { word: 'Apple', hint: 'A red or green fruit' },
        { word: 'Sushi', hint: 'Japanese rice dish' },
        { word: 'Burger', hint: 'Sandwich with a patty' },
        { word: 'Ice Cream', hint: 'Frozen dessert' },
        { word: 'Coffee', hint: 'Caffeinated morning drink' },
        { word: 'Chocolate', hint: 'Sweet treat from cocoa' },
        { word: 'Pasta', hint: 'Italian noodle dish' },
        { word: 'Steak', hint: 'Grilled beef' },
        { word: 'Salad', hint: 'Bowl of vegetables' },
        { word: 'Bread', hint: 'Baked dough' },
        { word: 'Cheese', hint: 'Dairy product' },
        { word: 'Chicken', hint: 'Common poultry' },
        { word: 'Egg', hint: 'Laid by hens' },
        { word: 'Banana', hint: 'Yellow curved fruit' },
        { word: 'Orange', hint: 'Citrus fruit' },
        { word: 'Grape', hint: 'Small round fruit' },
        { word: 'Strawberry', hint: 'Red berry' },
        { word: 'Potato', hint: 'Starch tuber' },
        { word: 'Tomato', hint: 'Red vegetable/fruit' },
        { word: 'Onion', hint: 'Makes you cry' },
        { word: 'Garlic', hint: 'Vampires hate it' },
        { word: 'Rice', hint: 'Small white grains' },
        { word: 'Tea', hint: 'Hot leaf drink' },
        { word: 'Juice', hint: 'Liquid from fruit' },
        { word: 'Sandwich', hint: 'Bread with filling' },
        { word: 'Waffle', hint: 'Grid breakfast' },
        { word: 'Pancake', hint: 'Flat breakfast cake' },
        { word: 'Donut', hint: 'Ring-shaped sweet' },
        { word: 'Cake', hint: 'Birthday dessert' },
        { word: 'Cookie', hint: 'Baked sweet snack' },
        { word: 'Pie', hint: 'Filled pastry' },
        { word: 'Soup', hint: 'Hot liquid dish' },
        { word: 'Noodles', hint: 'Long thin pasta' },
        { word: 'Pickle', hint: 'Sour preserved' },
    ],
    movies: [
        { word: 'Avatar', hint: 'Blue aliens movie' },
        { word: 'Titanic', hint: 'Sinking ship movie' },
        { word: 'Avengers', hint: 'Earths mightiest heroes' },
        { word: 'Star Wars', hint: 'Space saga' },
        { word: 'Jurassic Park', hint: 'Dinosaur theme park' },
        { word: 'The Lion King', hint: 'Circle of life' },
        { word: 'Frozen', hint: 'Let it go' },
        { word: 'Harry Potter', hint: 'The Boy Who Lived' },
        { word: 'Lord of the Rings', hint: 'One ring to rule them all' },
        { word: 'The Matrix', hint: 'Red or blue pill' },
        { word: 'Inception', hint: 'Dream within a dream' },
        { word: 'The Dark Knight', hint: 'Batman sequel' },
        { word: 'Toy Story', hint: 'Animated toys' },
        { word: 'Finding Nemo', hint: 'Lost clownfish' },
        { word: 'Shrek', hint: 'Green ogre' },
        { word: 'Spiderman', hint: 'Web slinger' },
        { word: 'Iron Man', hint: 'Tony Stark' },
        { word: 'Batman', hint: 'The Dark Knight' },
        { word: 'Superman', hint: 'Man of Steel' },
        { word: 'The Godfather', hint: 'Mafia classic' },
        { word: 'Forrest Gump', hint: 'Life is like a box of chocolates' },
        { word: 'Pulp Fiction', hint: 'Tarantino classic' },
        { word: 'The Shawshank Redemption', hint: 'Prison escape' },
        { word: 'Gladiator', hint: 'Roman warrior' },
        { word: 'Jaws', hint: 'Killer shark' },
        { word: 'E.T.', hint: 'Phone home' },
        { word: 'Back to the Future', hint: 'Time travel DeLorean' },
        { word: 'Rocky', hint: 'Boxing underdog' },
        { word: 'Interstellar', hint: 'Space exploration' },
        { word: 'Oppenheimer', hint: 'Atomic bomb creator' },
        { word: 'Barbie', hint: 'Famous doll movie' },
        { word: 'Top Gun', hint: 'Fighter pilot' },
        { word: 'Game of Thrones', hint: 'Fantasy TV series' },
        { word: 'Friends', hint: 'Classic sitcom' },
        { word: 'Breaking Bad', hint: 'Chemistry teacher turns criminal' },
        { word: 'Stranger Things', hint: 'Upside down world' },
        { word: 'The Office', hint: 'Mockumentary workplace' },
        { word: 'Squid Game', hint: 'Korean survival games' },
        { word: 'Wednesday', hint: 'Addams Family daughter' },
        { word: 'The Mandalorian', hint: 'This is the way' },
        { word: 'Black Panther', hint: 'Wakanda forever' },
        { word: 'Deadpool', hint: 'Merc with a mouth' },
        { word: 'Guardians of the Galaxy', hint: 'Space outlaws' },
        { word: 'Doctor Strange', hint: 'Master of mystic arts' },
        { word: 'Thor', hint: 'God of thunder' },
        { word: 'Captain America', hint: 'First Avenger' },
        { word: 'Wonder Woman', hint: 'Amazon warrior' },
        { word: 'Aquaman', hint: 'King of Atlantis' },
        { word: 'The Flash', hint: 'Fastest man alive' },
        { word: 'Dune', hint: 'Desert planet spice' },
        { word: 'Mad Max', hint: 'Post-apocalyptic wasteland' },
        { word: 'Terminator', hint: 'Ill be back' },
        { word: 'Alien', hint: 'Space horror' },
        { word: 'Predator', hint: 'Invisible hunter' },
        { word: 'Transformers', hint: 'Robots in disguise' },
        { word: 'Fast and Furious', hint: 'Street racing family' },
        { word: 'Mission Impossible', hint: 'Tom Cruise stunts' },
        { word: 'James Bond', hint: '007 spy' },
        { word: 'John Wick', hint: 'Legendary assassin' },
        { word: 'The Hunger Games', hint: 'Battle royale dystopia' },
        { word: 'Twilight', hint: 'Vampire romance' },
        { word: 'Pirates of the Caribbean', hint: 'Captain Jack Sparrow' },
        { word: 'Moana', hint: 'Ocean voyager' },
        { word: 'Encanto', hint: 'We dont talk about Bruno' },
    ],
    games: [
        { word: 'Minecraft', hint: 'Block building game' },
        { word: 'Fortnite', hint: 'Battle royale game' },
        { word: 'Roblox', hint: 'Online game platform' },
        { word: 'Among Us', hint: 'Imposter game' },
        { word: 'Call of Duty', hint: 'War shooter game' },
        { word: 'Grand Theft Auto', hint: 'Open world crime' },
        { word: 'FIFA', hint: 'Soccer simulation' },
        { word: 'Pokémon', hint: 'Gotta catch em all' },
        { word: 'Mario', hint: 'Italian plumber' },
        { word: 'Zelda', hint: 'Link saves Hyrule' },
        { word: 'Sonic', hint: 'Blue hedgehog' },
        { word: 'Pac-Man', hint: 'Yellow dot eater' },
        { word: 'Tetris', hint: 'Falling blocks puzzle' },
        { word: 'League of Legends', hint: 'MOBA game' },
        { word: 'Dota', hint: 'Defense of the Ancients' },
        { word: 'Valorant', hint: 'Tactical shooter' },
        { word: 'Counter-Strike', hint: 'Terrorists vs CT' },
        { word: 'Overwatch', hint: 'Hero shooter' },
        { word: 'Apex Legends', hint: 'Battle royale legends' },
        { word: 'PUBG', hint: 'PlayerUnknowns Battlegrounds' },
        { word: 'Rocket League', hint: 'Soccer with cars' },
        { word: 'Fall Guys', hint: 'Obstacle course beans' },
        { word: 'Candy Crush', hint: 'Match-3 puzzle' },
        { word: 'Angry Birds', hint: 'Slingshot birds' },
        { word: 'Clash of Clans', hint: 'Village builder' },
        { word: 'Clash Royale', hint: 'Card battle arena' },
        { word: 'Subway Surfers', hint: 'Endless runner' },
        { word: 'Temple Run', hint: 'Run from monkey' },
        { word: 'Fruit Ninja', hint: 'Slice fruit' },
        { word: 'The Sims', hint: 'Life simulation' },
        { word: 'Animal Crossing', hint: 'Island life' },
        { word: 'Stardew Valley', hint: 'Farming simulator' },
        { word: 'Terraria', hint: '2D sandbox adventure' },
        { word: 'Undertale', hint: 'Spare or fight' },
        { word: 'Cuphead', hint: 'Cartoon boss rush' },
        { word: 'Hollow Knight', hint: 'Bug metroidvania' },
        { word: 'Celeste', hint: 'Mountain climbing platformer' },
        { word: 'Hades', hint: 'Greek underworld roguelike' },
        { word: 'Dark Souls', hint: 'You died' },
        { word: 'Elden Ring', hint: 'Open world souls' },
        { word: 'Skyrim', hint: 'Fus Ro Dah' },
        { word: 'Fallout', hint: 'Post-nuclear wasteland' },
        { word: 'The Witcher', hint: 'Geralt monster hunter' },
        { word: 'Red Dead Redemption', hint: 'Wild west outlaw' },
        { word: 'Assassins Creed', hint: 'Historical parkour' },
        { word: 'God of War', hint: 'Kratos rage' },
        { word: 'The Last of Us', hint: 'Zombie survival' },
        { word: 'Uncharted', hint: 'Treasure hunter' },
        { word: 'Spider-Man', hint: 'Web-swinging hero' },
        { word: 'Batman Arkham', hint: 'Dark Knight detective' },
        { word: 'Mortal Kombat', hint: 'Finish him' },
        { word: 'Street Fighter', hint: 'Hadouken' },
        { word: 'Super Smash Bros', hint: 'Nintendo brawler' },
        { word: 'Tekken', hint: 'King of Iron Fist' },
        { word: 'Resident Evil', hint: 'Zombie horror' },
        { word: 'Silent Hill', hint: 'Psychological horror' },
        { word: 'Five Nights at Freddys', hint: 'Animatronic horror' },
        { word: 'Genshin Impact', hint: 'Anime open world' },
        { word: 'Honkai Star Rail', hint: 'Space fantasy RPG' },
        { word: 'Final Fantasy', hint: 'JRPG classic' },
        { word: 'Dragon Quest', hint: 'Slime adventure' },
        { word: 'Persona', hint: 'Social link RPG' },
        { word: 'Metal Gear Solid', hint: 'Stealth espionage' },
        { word: 'Halo', hint: 'Master Chief' },
    ],
    objects: [
        { word: 'Chair', hint: 'You sit on it' },
        { word: 'Phone', hint: 'Used for calling' },
        { word: 'Shoe', hint: 'Worn on feet' },
        { word: 'Key', hint: 'Unlocks doors' },
        { word: 'Table', hint: 'Furniture with legs' },
        { word: 'Car', hint: 'Road vehicle' },
        { word: 'Pen', hint: 'Writes with ink' },
        { word: 'Paper', hint: 'Write on this' },
        { word: 'Bag', hint: 'Carry things in it' },
        { word: 'Watch', hint: 'Wear on wrist' },
        { word: 'Glasses', hint: 'Helps vision' },
        { word: 'Hat', hint: 'Worn on head' },
        { word: 'Umbrella', hint: 'Protect from rain' },
        { word: 'Bottle', hint: 'Holds liquid' },
        { word: 'Knife', hint: 'Used to cut' },
        { word: 'Spoon', hint: 'Used to eat soup' },
        { word: 'Fork', hint: 'Used to pierce food' },
        { word: 'Plate', hint: 'Eat off this' },
        { word: 'Cup', hint: 'Drink from this' },
        { word: 'Bed', hint: 'Sleep on this' },
        { word: 'Laptop', hint: 'Portable PC' },
        { word: 'Camera', hint: 'Takes photos' },
        { word: 'Mirror', hint: 'Reflects image' },
        { word: 'Soap', hint: 'Cleans body' },
        { word: 'Towel', hint: 'Dries you off' },
        { word: 'Comb', hint: 'Styles hair' },
        { word: 'Scissors', hint: 'Cutting tool' },
        { word: 'Needle', hint: 'Sewing tool' },
        { word: 'Thread', hint: 'For sewing' },
        { word: 'Button', hint: 'Fastens clothes' },
        { word: 'Zipper', hint: 'Quick fastener' },
        { word: 'Wallet', hint: 'Holds money' },
        { word: 'Backpack', hint: 'Carries books' },
    ],
    trends: [
        { word: 'AI', hint: 'Artificial Intelligence' },
        { word: 'Crypto', hint: 'Digital currency' },
        { word: 'Influencer', hint: 'Famous on social media' },
        { word: 'Streaming', hint: 'Live broadcasting' },
        { word: 'Meme', hint: 'Funny internet picture' },
        { word: 'Viral', hint: 'Spreads fast online' },
        { word: 'Selfie', hint: 'Photo of yourself' },
        { word: 'Hashtag', hint: 'Used on Twitter/Insta' },
        { word: 'Podcast', hint: 'Audio show' },
        { word: 'Vlog', hint: 'Video blog' },
        { word: 'NFT', hint: 'Digital collectible' },
        { word: 'Metaverse', hint: 'Virtual world' },
        { word: 'Remote Work', hint: 'Working from home' },
        { word: 'Drone', hint: 'Flying robot' },
        { word: 'Electric Car', hint: 'Tesla' },
        { word: 'Smartwatch', hint: 'Wearable tech' },
        { word: 'Filter', hint: 'Changes photo look' },
        { word: 'Reel', hint: 'Short Instagram video' },
        { word: 'Challenge', hint: 'Trending task' },
        { word: 'Algorithm', hint: 'Controls feed' },
        { word: 'Troll', hint: 'Internet pest' },
        { word: 'Bot', hint: 'Automated account' },
        { word: 'App', hint: 'Software on phone' },
        { word: 'Cloud', hint: 'Online storage' },
        { word: 'Wi-Fi', hint: 'Wireless internet' },
        { word: 'Emoji', hint: 'Digital emotion icons' },
        { word: 'GIF', hint: 'Moving image' },
        { word: 'Screenshot', hint: 'Capture phone screen' },
        { word: 'Notification', hint: 'Phone alert' },
        { word: 'Download', hint: 'Get from internet' },
        { word: 'Upload', hint: 'Send to internet' },
        { word: 'Password', hint: 'Login security' },
    ],
    sport: [
        { word: 'Soccer', hint: 'Football (World)' },
        { word: 'Basketball', hint: 'Hoops and dunking' },
        { word: 'Cricket', hint: 'Bat and ball' },
        { word: 'Tennis', hint: 'Racket and yellow ball' },
        { word: 'Golf', hint: 'Clubs and holes' },
        { word: 'Volleyball', hint: 'Net and spike' },
        { word: 'Swimming', hint: 'Water racing' },
        { word: 'Boxing', hint: 'Fighting with gloves' },
        { word: 'Running', hint: 'Track usually' },
        { word: 'Yoga', hint: 'Stretching poses' },
        { word: 'Gymnastics', hint: 'Flips and balance' },
        { word: 'Skiing', hint: 'Snow sliding' },
        { word: 'Surfing', hint: 'Riding waves' },
        { word: 'Skating', hint: 'Ice or wheels' },
        { word: 'Hockey', hint: 'Puck and stick' },
        { word: 'Rugby', hint: 'Oval ball contact' },
        { word: 'Baseball', hint: 'Bat and diamond' },
        { word: 'Badminton', hint: 'Shuttlecock' },
        { word: 'Table Tennis', hint: 'Ping pong' },
        { word: 'Cycling', hint: 'Bike racing' },
        { word: 'Wrestling', hint: 'Grappling' },
        { word: 'Karate', hint: 'Martial art' },
        { word: 'Marathon', hint: 'Long race' },
        { word: 'Sprinting', hint: 'Fast race' },
        { word: 'Medal', hint: 'Gold, Silver, Bronze' },
        { word: 'Trophy', hint: 'Winner prize' },
        { word: 'Stadium', hint: 'Sports venue' },
        { word: 'Coach', hint: 'Team trainer' },
        { word: 'Referee', hint: 'Game judge' },
        { word: 'Whistle', hint: 'Referee tool' },
        { word: 'Goal', hint: 'Score point' },
        { word: 'Team', hint: 'Group of players' },
    ],
    dailyLife: [
        { word: 'Traffic', hint: 'Cars on road' },
        { word: 'Shopping', hint: 'Buying things' },
        { word: 'Cooking', hint: 'Making food' },
        { word: 'Cleaning', hint: 'Tidying up' },
        { word: 'Meeting', hint: 'Gathering at work' },
        { word: 'Email', hint: 'Digital letter' },
        { word: 'Salary', hint: 'Pay for work' },
        { word: 'Rent', hint: 'Pay for house' },
        { word: 'Bus', hint: 'Public transport' },
        { word: 'Train', hint: 'Rail transport' },
        { word: 'Alarm', hint: 'Wakes you up' },
        { word: 'Breakfast', hint: 'Morning meal' },
        { word: 'Lunch', hint: 'Midday meal' },
        { word: 'Dinner', hint: 'Evening meal' },
        { word: 'Shower', hint: 'Bathing' },
        { word: 'Walking', hint: 'Moving on legs' },
        { word: 'Sleeping', hint: 'Resting eyes' },
        { word: 'Talking', hint: 'Speaking' },
        { word: 'Listening', hint: 'Hearing' },
        { word: 'Reading', hint: 'Looking at text' },
        { word: 'Writing', hint: 'Pen on paper' },
        { word: 'Drawing', hint: 'Creating art' },
        { word: 'Party', hint: 'Celebration' },
        { word: 'Wedding', hint: 'Marriage ceremony' },
        { word: 'Birthday', hint: 'Age celebration' },
        { word: 'Holiday', hint: 'Day off' },
        { word: 'Vacation', hint: 'Long break' },
        { word: 'Weekend', hint: 'Saturday Sunday' },
        { word: 'Morning', hint: 'Early day' },
        { word: 'Evening', hint: 'Late day' },
        { word: 'Midnight', hint: '12 AM' },
        { word: 'Noon', hint: '12 PM' },
    ],
    things: [
        { word: 'Box', hint: 'Container' },
        { word: 'Ball', hint: 'Round object' },
        { word: 'Ring', hint: 'Worn on finger' },
        { word: 'Chain', hint: 'Linked metal' },
        { word: 'Lock', hint: 'Secures things' },
        { word: 'Key', hint: 'Opens lock' },
        { word: 'Door', hint: 'Entryway' },
        { word: 'Window', hint: 'Look through it' },
        { word: 'Wall', hint: 'Brick divider' },
        { word: 'Floor', hint: 'Stand on it' },
        { word: 'Roof', hint: 'Top of house' },
        { word: 'Fan', hint: 'Moves air' },
        { word: 'Lamp', hint: 'Gives light' },
        { word: 'Candle', hint: 'Wax light' },
        { word: 'Soap', hint: 'Cleaning bar' },
        { word: 'Toothbrush', hint: 'Cleans teeth' },
        { word: 'Pillow', hint: 'Head rest' },
        { word: 'Blanket', hint: 'Keeps warm' },
        { word: 'Curtain', hint: 'Covers window' },
        { word: 'Carpet', hint: 'Floor rug' },
        { word: 'Vase', hint: 'Holds flowers' },
        { word: 'Pot', hint: 'Cooking vessel' },
        { word: 'Pan', hint: 'Frying vessel' },
        { word: 'Ladder', hint: 'Climb up' },
        { word: 'Hammer', hint: 'Hits nails' },
        { word: 'Screw', hint: 'Threaded fastener' },
        { word: 'Nail', hint: 'Metal pin' },
        { word: 'Drill', hint: 'Makes holes' },
        { word: 'Paint', hint: 'Colors walls' },
        { word: 'Brush', hint: 'Applies paint' },
        { word: 'Rope', hint: 'Thick string' },
        { word: 'Tape', hint: 'Sticky strip' },
    ],
    science: [
        { word: 'Atom', hint: 'Basic unit of matter' },
        { word: 'Gravity', hint: 'Keeps us on ground' },
        { word: 'Galaxy', hint: 'Collection of stars' },
        { word: 'DNA', hint: 'Genetic code' },
        { word: 'Robot', hint: 'Mechanical helper' },
        { word: 'Virus', hint: 'Microscopic agent' },
        { word: 'Laser', hint: 'Focused light beam' },
        { word: 'Magnet', hint: 'Attracts iron' },
        { word: 'Fossil', hint: 'Old bone in rock' },
        { word: 'Volcano', hint: 'Erupts with lava' },
        { word: 'Planet', hint: 'Orbits a star' },
        { word: 'Telescope', hint: 'See far away' },
        { word: 'Microscope', hint: 'See tiny things' },
        { word: 'Battery', hint: 'Stores energy' },
        { word: 'Satellite', hint: 'Orbits Earth' },
        { word: 'Rocket', hint: 'Goes to space' },
        { word: 'Astronaut', hint: 'Space traveler' },
        { word: 'Laboratory', hint: 'Science work place' },
        { word: 'Chemical', hint: 'Reactive substance' },
        { word: 'Beaker', hint: 'Glass container' },
        { word: 'Formula', hint: 'Math recipe' },
        { word: 'Experiment', hint: 'Scientific test' },
        { word: 'Evolution', hint: 'Change over time' },
        { word: 'Black Hole', hint: 'Light cannot escape' },
        { word: 'Meteor', hint: 'Falling star' },
    ],
    history: [
        { word: 'Pyramid', hint: 'Egyptian tomb' },
        { word: 'Knight', hint: 'Medieval warrior' },
        { word: 'Castle', hint: 'Fortified home' },
        { word: 'Viking', hint: 'Norse seafarer' },
        { word: 'Samurai', hint: 'Japanese warrior' },
        { word: 'Gladiator', hint: 'Roman fighter' },
        { word: 'Pharaoh', hint: 'Egyptian king' },
        { word: 'Mummy', hint: 'Wrapped body' },
        { word: 'Sword', hint: 'Sharp weapon' },
        { word: 'Shield', hint: 'Protection tool' },
        { word: 'Crown', hint: 'Royal hat' },
        { word: 'Throne', hint: 'Royal chair' },
        { word: 'Empire', hint: 'Large kingdom' },
        { word: 'War', hint: 'Large conflict' },
        { word: 'Peace', hint: 'No fighting' },
        { word: 'Revolution', hint: 'Big change' },
        { word: 'Discovery', hint: 'Finding new lands' },
        { word: 'Ancient', hint: 'Very old' },
        { word: 'Coin', hint: 'Metal money' },
        { word: 'Map', hint: 'Guide to places' },
    ],
    mythology: [
        { word: 'Dragon', hint: 'Fire breathing lizard' },
        { word: 'Unicorn', hint: 'Horse with horn' },
        { word: 'Mermaid', hint: 'Fish woman' },
        { word: 'Zeus', hint: 'Greek god of sky' },
        { word: 'Thor', hint: 'Norse god of thunder' },
        { word: 'Hercules', hint: 'Strong hero' },
        { word: 'Phoenix', hint: 'Fire bird' },
        { word: 'Ghost', hint: 'Spirit' },
        { word: 'Vampire', hint: 'Drinks blood' },
        { word: 'Werewolf', hint: 'Wolf man' },
        { word: 'Wizard', hint: 'User of magic' },
        { word: 'Witch', hint: 'Magic woman' },
        { word: 'Fairy', hint: 'Small magical flyer' },
        { word: 'Elf', hint: 'Pointy eared' },
        { word: 'Giant', hint: 'Very big person' },
        { word: 'Angel', hint: 'Divine being' },
        { word: 'Demon', hint: 'Evil spirit' },
        { word: 'Medusa', hint: 'Snake hair' },
        { word: 'Poseidon', hint: 'God of sea' },
        { word: 'Hades', hint: 'God of underword' },
    ],
    nature: [
        { word: 'Flower', hint: 'Colorful plant part' },
        { word: 'Grass', hint: 'Green ground cover' },
        { word: 'Cactus', hint: 'Spiky desert plant' },
        { word: 'Rose', hint: 'Love flower' },
        { word: 'Sunflower', hint: 'Follows the sun' },
        { word: 'Palm Tree', hint: 'Tropical tree' },
        { word: 'Leaf', hint: 'On a branch' },
        { word: 'Root', hint: 'Underground plant part' },
        { word: 'Seed', hint: 'Starts a plant' },
        { word: 'Soil', hint: 'Dirt for plants' },
        { word: 'Mushroom', hint: 'Fungi' },
        { word: 'Bamboo', hint: 'Panda food' },
        { word: 'Vine', hint: 'Climbing plant' },
        { word: 'Forest', hint: 'Many trees' },
        { word: 'Jungle', hint: 'Thick forest' },
        { word: 'River', hint: 'Flowing water' },
        { word: 'Ocean', hint: 'Salty water' },
        { word: 'Desert', hint: 'Dry sandy place' },
        { word: 'Mountain', hint: 'High rock' },
        { word: 'Valley', hint: 'Low land' },
        { word: 'Canyon', hint: 'Deep gorge' },
        { word: 'Cliff', hint: 'Steep drop' },
        { word: 'Cave', hint: 'Dark hole in rock' },
        { word: 'Beach', hint: 'Sand by sea' },
        { word: 'Island', hint: 'Surrounded by water' },
        { word: 'Volcano', hint: 'Erupts lava' },
        { word: 'Rainforest', hint: 'Wet jungle' },
        { word: 'Swamp', hint: 'Wet muddy land' },
        { word: 'Lake', hint: 'Inland water' },
        { word: 'Pond', hint: 'Small lake' },
    ],
    tech: [
        { word: 'Robot', hint: 'Automated machine' },
        { word: 'Computer', hint: 'Think machine' },
        { word: 'Internet', hint: 'World wide web' },
        { word: 'Software', hint: 'Code programs' },
        { word: 'Hardware', hint: 'Physical parts' },
        { word: 'Keyboard', hint: 'Typing tool' },
        { word: 'Mouse', hint: 'Clicking tool' },
        { word: 'Screen', hint: 'Display' },
        { word: 'Battery', hint: 'Power cell' },
        { word: 'Charger', hint: 'Refills battery' },
        { word: 'Cable', hint: 'Wire connector' },
        { word: 'Wifi', hint: 'Wireless net' },
        { word: 'Bluetooth', hint: 'Short range wireless' },
        { word: 'Server', hint: 'Hosts data' },
        { word: 'Cloud', hint: 'Remote storage' },
        { word: 'Database', hint: 'Stores info' },
        { word: 'Pixel', hint: 'Dot on screen' },
        { word: 'Bug', hint: 'Error in code' },
        { word: 'Hacker', hint: 'Breaks security' },
        { word: 'Virus', hint: 'Malware' },
        { word: 'Firewall', hint: 'Network protection' },
        { word: 'Encryption', hint: 'Secret code' },
        { word: 'Password', hint: 'Secret key' },
        { word: 'Email', hint: 'Digital mail' },
        { word: 'Chat', hint: 'Online talk' },
        { word: 'Video Game', hint: 'Digital play' },
        { word: 'Console', hint: 'Gaming box' },
        { word: 'Controller', hint: 'Game input' },
        { word: 'Headphones', hint: 'Ear speakers' },
        { word: 'Microphone', hint: 'Voice input' },
    ],
    fashion: [
        { word: 'Dress', hint: 'One piece cloth' },
        { word: 'Skirt', hint: 'Lower body cloth' },
        { word: 'Shirt', hint: 'Upper body cloth' },
        { word: 'Pants', hint: 'Leg covering' },
        { word: 'Jeans', hint: 'Denim pants' },
        { word: 'Jacket', hint: 'Outer wear' },
        { word: 'Coat', hint: 'Warm outer wear' },
        { word: 'Hat', hint: 'Head wear' },
        { word: 'Cap', hint: 'Casual hat' },
        { word: 'Scarf', hint: 'Neck warmer' },
        { word: 'Gloves', hint: 'Hand warmers' },
        { word: 'Socks', hint: 'Foot covers' },
        { word: 'Shoes', hint: 'Foot wear' },
        { word: 'Boots', hint: 'High shoes' },
        { word: 'Heels', hint: 'Tall shoes' },
        { word: 'Sneakers', hint: 'Sport shoes' },
        { word: 'Belt', hint: 'Holds pants' },
        { word: 'Tie', hint: 'Formal neck wear' },
        { word: 'Suit', hint: 'Formal set' },
        { word: 'Watch', hint: 'Wrist time' },
        { word: 'Ring', hint: 'Finger jewelry' },
        { word: 'Necklace', hint: 'Neck jewelry' },
        { word: 'Earring', hint: 'Ear jewelry' },
        { word: 'Bracelet', hint: 'Wrist jewelry' },
        { word: 'Purse', hint: 'Hand bag' },
        { word: 'Wallet', hint: 'Money holder' },
        { word: 'Glasses', hint: 'Eye aid' },
        { word: 'Sunglasses', hint: 'Dark glasses' },
        { word: 'Makeup', hint: 'Face paint' },
        { word: 'Perfume', hint: 'Nice smell' },
    ],
    football: [
        // LEGENDS
        { word: 'Pelé', hint: 'Brazil Legend' },
        { word: 'Maradona', hint: 'Hand of God' },
        { word: 'Zidane', hint: 'Headbutt final' },
        { word: 'Ronaldinho', hint: 'Joga Bonito' },
        { word: 'Ronaldo Nazário', hint: 'R9 Phenomenon' },
        { word: 'Thierry Henry', hint: 'Arsenal King' },
        { word: 'Johan Cruyff', hint: 'Total Football' },
        { word: 'Paolo Maldini', hint: 'Milan Defender' },
        { word: 'Beckham', hint: 'Free kick master' },
        { word: 'Rooney', hint: 'Man Utd Legend' },
        { word: 'Gerrard', hint: 'Liverpool Captain' },
        { word: 'Lampard', hint: 'Chelsea Goalscorer' },
        { word: 'Scholes', hint: 'Ginger Prince' },
        { word: 'Kaka', hint: 'Last human Ballon d\'Or' },
        { word: 'Pirlo', hint: 'The Architect' },
        { word: 'Iniesta', hint: 'World Cup winner' },
        { word: 'Xavi', hint: 'Master passer' },
        { word: 'Buffon', hint: 'Italian Goalkeeper' },
        { word: 'Cannavaro', hint: 'Ballon d\'Or Defender' },
        { word: 'Totti', hint: 'Roma Prince' },

        // MODERN STARS
        { word: 'Haaland', hint: 'Robot striker' },
        { word: 'Mbappé', hint: 'French Speedster' },
        { word: 'Bellingham', hint: 'Hey Jude' },
        { word: 'Vinicius Jr', hint: 'Real Madrid Winger' },
        { word: 'De Bruyne', hint: 'Man City Playmaker' },
        { word: 'Salah', hint: 'Egyptian King' },
        { word: 'Lewandowski', hint: 'Goal Machine' },
        { word: 'Neymar', hint: 'Brazilian Skill' },
        { word: 'Modric', hint: 'Croatian Magician' },
        { word: 'Harry Kane', hint: 'Spurs/Bayern Striker' },
        { word: 'Son Heung-min', hint: 'Korean Star' },
        { word: 'Van Dijk', hint: 'Liverpool Wall' },
        { word: 'Rashford', hint: 'Man Utd Winger' },
        { word: 'Saka', hint: 'Arsenal Starboy' },
        { word: 'Pedri', hint: 'Barca Wonderkid' },
        { word: 'Lamine Yamal', hint: 'Teenage Sensation' },

        // STREETS WON'T FORGET / CULT HEROES
        { word: 'Ben Arfa', hint: 'Wasted Talent' },
        { word: 'Adel Taarabt', hint: 'QPR Magician' },
        { word: 'Michu', hint: 'One Season Wonder' },
        { word: 'Payet', hint: 'West Ham Free Kicks' },
        { word: 'Quaresma', hint: 'Trivela King' },
        { word: 'Jay-Jay Okocha', hint: 'So good they named him twice' },
        { word: 'Balotelli', hint: 'Why Always Me?' },
        { word: 'Zlatan', hint: 'Dare to Zlatan' },
        { word: 'Berbatov', hint: 'Lazy Genius' },
        { word: 'Akinfenwa', hint: 'Strongest Player' },
        { word: 'Giroud', hint: 'Puskas Winner' },
        { word: 'Suarez', hint: 'Biter / Striker' },
        { word: 'Bale', hint: 'Wales. Golf. Madrid.' },
        { word: 'Hazard', hint: 'Chelsea Chelsea Chelsea' },
        { word: 'Aguero', hint: 'City Title Winner' },
        { word: 'Drogba', hint: 'Chelsea Legend' },
        { word: 'Yaya Toure', hint: 'Cake Box to Box' },

        // TEAMS
        { word: 'Real Madrid', hint: 'Los Blancos' },
        { word: 'Barcelona', hint: 'Camp Nou' },
        { word: 'Man Utd', hint: 'Red Devils' },
        { word: 'Liverpool', hint: 'You\'ll Never Walk Alone' },
        { word: 'Arsenal', hint: 'Gunners' },
        { word: 'Chelsea', hint: 'The Blues' },
        { word: 'Man City', hint: 'Citizens' },
        { word: 'Bayern Munich', hint: 'German Giants' },
        { word: 'Dortmund', hint: 'Yellow Wall' },
        { word: 'Juventus', hint: 'Old Lady' },
        { word: 'AC Milan', hint: 'Rossoneri' },
        { word: 'Inter Milan', hint: 'Nerazzurri' },
        { word: 'PSG', hint: 'Paris Team' },
        { word: 'Ajax', hint: 'Dutch Academy' },
        { word: 'Boca Juniors', hint: 'Argentina Blue/Gold' },
        { word: 'Flamengo', hint: 'Brazil Red/Black' },
        { word: 'Al Nassr', hint: 'CR7 Team' },
        { word: 'Inter Miami', hint: 'Messi Team' },
    ],
    basketball: [
        // LEGENDS
        { word: 'Michael Jordan', hint: 'GOAT' },
        { word: 'LeBron James', hint: 'King James' },
        { word: 'Kobe Bryant', hint: 'Black Mamba' },
        { word: 'Magic Johnson', hint: 'Showtime Lakers' },
        { word: 'Larry Bird', hint: 'Boston Legend' },
        { word: 'Shaquille O\'Neal', hint: 'Diesel' },
        { word: 'Tim Duncan', hint: 'Big Fundamental' },
        { word: 'Kareem Abdul-Jabbar', hint: 'Skyhook' },
        { word: 'Wilt Chamberlain', hint: '100 points' },
        { word: 'Bill Russell', hint: '11 rings' },
        { word: 'Allen Iverson', hint: 'The Answer' },
        { word: 'Dirk Nowitzki', hint: 'German Legend' },
        { word: 'Hakeem Olajuwon', hint: 'Dream Shake' },
        { word: 'Charles Barkley', hint: 'Round Mound' },
        { word: 'Scottie Pippen', hint: 'Jordan\'s Partner' },

        // MODERN STARS
        { word: 'Stephen Curry', hint: 'Chef Curry' },
        { word: 'Kevin Durant', hint: 'Slim Reaper' },
        { word: 'Giannis', hint: 'Greek Freak' },
        { word: 'Luka Doncic', hint: 'Slovenian Wonder' },
        { word: 'Nikola Jokic', hint: 'Joker' },
        { word: 'Joel Embiid', hint: 'The Process' },
        { word: 'Jayson Tatum', hint: 'Celtics Star' },
        { word: 'Anthony Davis', hint: 'The Brow' },
        { word: 'Damian Lillard', hint: 'Dame Time' },
        { word: 'Kawhi Leonard', hint: 'The Claw' },
        { word: 'Jimmy Butler', hint: 'Playoff Jimmy' },
        { word: 'Kyrie Irving', hint: 'Uncle Drew' },
        { word: 'James Harden', hint: 'The Beard' },
        { word: 'Russell Westbrook', hint: 'Mr. Triple Double' },
        { word: 'Paul George', hint: 'PG-13' },

        // TEAMS
        { word: 'Lakers', hint: 'Purple and Gold' },
        { word: 'Celtics', hint: 'Boston Green' },
        { word: 'Warriors', hint: 'Golden State' },
        { word: 'Bulls', hint: 'Chicago Dynasty' },
        { word: 'Heat', hint: 'Miami Vice' },
        { word: 'Spurs', hint: 'San Antonio' },
        { word: 'Knicks', hint: 'New York' },
        { word: 'Nets', hint: 'Brooklyn' },
        { word: 'Bucks', hint: 'Milwaukee' },
        { word: 'Mavericks', hint: 'Dallas' },
        { word: 'Nuggets', hint: 'Denver' },
        { word: 'Suns', hint: 'Phoenix' },
        { word: 'Sixers', hint: 'Philadelphia' },
        { word: 'Raptors', hint: 'Toronto' },
        { word: 'Clippers', hint: 'LA Clippers' },
    ],
    ballKnowledge: [
        // Combined from football and basketball
    ],
    genZ: [
        // Social Media
        { word: 'TikTok', hint: 'Short video app' },
        { word: 'Instagram', hint: 'Photo sharing' },
        { word: 'Snapchat', hint: 'Disappearing messages' },
        { word: 'YouTube Shorts', hint: 'Short videos' },
        
        // Classic Slang
        { word: 'Slay', hint: 'Do great' },
        { word: 'No Cap', hint: 'No lie' },
        { word: 'Bussin', hint: 'Really good' },
        { word: 'Sheesh', hint: 'Wow expression' },
        { word: 'Vibe Check', hint: 'Mood assessment' },
        { word: 'Main Character', hint: 'Living your best life' },
        { word: 'Rizz', hint: 'Charisma' },
        { word: 'Simp', hint: 'Over-admirer' },
        { word: 'Stan', hint: 'Super fan' },
        { word: 'Ghosting', hint: 'Disappearing act' },
        { word: 'FOMO', hint: 'Fear of missing out' },
        { word: 'Lowkey', hint: 'Kind of/secretly' },
        { word: 'Highkey', hint: 'Obviously/very' },
        { word: 'Bet', hint: 'Okay/sure' },
        
        // Brainrot Core
        { word: 'Skibidi Toilet', hint: 'Viral meme series' },
        { word: 'Sigma', hint: 'Lone wolf mindset' },
        { word: 'Alpha', hint: 'Dominant personality' },
        { word: 'Beta', hint: 'Submissive type' },
        { word: 'Gyatt', hint: 'Exclamation of surprise' },
        { word: 'Ohio', hint: 'Weird/cursed place' },
        { word: 'Fanum Tax', hint: 'Taking someone\'s food' },
        { word: 'Griddy', hint: 'Victory dance' },
        { word: 'Mewing', hint: 'Jaw exercise trend' },
        { word: 'Mogging', hint: 'Outshining someone' },
        { word: 'Looksmaxxing', hint: 'Improving appearance' },
        { word: 'Goon Cave', hint: 'Personal space' },
        { word: 'NPC', hint: 'Non-playable character' },
        { word: 'Caught in 4K', hint: 'Caught red-handed' },
        { word: 'Ratio', hint: 'Getting more likes' },
        { word: 'L + Ratio', hint: 'Double insult' },
        { word: 'Touch Grass', hint: 'Go outside' },
        { word: 'Based', hint: 'Authentic/cool' },
        { word: 'Cringe', hint: 'Embarrassing' },
        { word: 'Mid', hint: 'Mediocre' },
        { word: 'W', hint: 'Win' },
        { word: 'L', hint: 'Loss' },
        { word: 'Ick', hint: 'Turn-off' },
        { word: 'Delulu', hint: 'Delusional' },
        { word: 'Yapping', hint: 'Talking too much' },
        { word: 'Cooked', hint: 'Done for/finished' },
        { word: 'It\'s Giving', hint: 'It seems like' },
        { word: 'Ate', hint: 'Did amazing' },
        { word: 'Devious Lick', hint: 'Stealing trend' },
        { word: 'Unhinged', hint: 'Wild/crazy' },
        { word: 'Snatched', hint: 'Looking good' },
        { word: 'Periodt', hint: 'End of discussion' },
        { word: 'Cheugy', hint: 'Out of style' },
        { word: 'Hits Different', hint: 'Feels special' },
        { word: 'Rent Free', hint: 'Can\'t stop thinking' },
        { word: 'Gatekeep', hint: 'Keep secret' },
        { word: 'Gaslight', hint: 'Manipulate' },
        { word: 'Girlboss', hint: 'Female entrepreneur' },
        { word: 'Slay Queen', hint: 'Confident woman' },
        { word: 'Toxic', hint: 'Harmful behavior' },
        { word: 'Red Flag', hint: 'Warning sign' },
        { word: 'Green Flag', hint: 'Good sign' },
        { word: 'Beige Flag', hint: 'Neutral quirk' },
        { word: 'Situationship', hint: 'Undefined relationship' },
        { word: 'Soft Launch', hint: 'Subtle reveal' },
        { word: 'Hard Launch', hint: 'Official announcement' },
    ],
    famousPeople: [
        { word: 'Albert Einstein', hint: 'Theory of Relativity' },
        { word: 'Marilyn Monroe', hint: 'Blonde icon' },
        { word: 'Michael Jackson', hint: 'King of Pop' },
        { word: 'Barack Obama', hint: '44th US President' },
        { word: 'Donald Trump', hint: 'Billionaire President' },
        { word: 'Elon Musk', hint: 'Tesla & SpaceX' },
        { word: 'Steve Jobs', hint: 'Apple founder' },
        { word: 'Bill Gates', hint: 'Microsoft founder' },
        { word: 'Queen Elizabeth II', hint: 'British Monarch' },
        { word: 'Princess Diana', hint: 'People\'s Princess' },
        { word: 'Martin Luther King Jr', hint: 'I Have a Dream' },
        { word: 'Nelson Mandela', hint: 'Anti-apartheid leader' },
        { word: 'Mahatma Gandhi', hint: 'Non-violent leader' },
        { word: 'Cristiano Ronaldo', hint: 'CR7' },
        { word: 'Lionel Messi', hint: 'Argentine GOAT' },
        { word: 'LeBron James', hint: 'King James' },
        { word: 'Serena Williams', hint: 'Tennis Queen' },
        { word: 'Muhammad Ali', hint: 'Float like a butterfly' },
        { word: 'Mike Tyson', hint: 'Iron Mike' },
        { word: 'Usain Bolt', hint: 'Fastest man' },
        { word: 'Taylor Swift', hint: 'Eras Tour' },
        { word: 'Beyoncé', hint: 'Queen Bey' },
        { word: 'Kanye West', hint: 'Yeezy' },
        { word: 'Eminem', hint: 'Slim Shady' },
        { word: 'Rihanna', hint: 'Umbrella singer' },
        { word: 'Kim Kardashian', hint: 'Reality TV star' },
        { word: 'Kylie Jenner', hint: 'Lip kit mogul' },
        { word: 'Dwayne Johnson', hint: 'The Rock' },
        { word: 'Kevin Hart', hint: 'Short comedian' },
        { word: 'Will Smith', hint: 'Fresh Prince' },
        { word: 'Tom Cruise', hint: 'Mission Impossible' },
        { word: 'Brad Pitt', hint: 'Fight Club star' },
        { word: 'Angelina Jolie', hint: 'Tomb Raider' },
        { word: 'Leonardo DiCaprio', hint: 'Titanic star' },
        { word: 'Johnny Depp', hint: 'Captain Jack Sparrow' },
        { word: 'Robert Downey Jr', hint: 'Iron Man' },
        { word: 'Chris Hemsworth', hint: 'Thor actor' },
        { word: 'Ryan Reynolds', hint: 'Deadpool actor' },
        { word: 'Zendaya', hint: 'MJ in Spider-Man' },
        { word: 'Tom Holland', hint: 'Spider-Man actor' },
        { word: 'Justin Bieber', hint: 'Baby singer' },
        { word: 'Harry Styles', hint: 'One Direction alum' },
        { word: 'Drake', hint: 'Canadian rapper' },
        { word: 'The Weeknd', hint: 'Blinding Lights' },
        { word: 'Ariana Grande', hint: 'High ponytail' },
        { word: 'Billie Eilish', hint: 'Bad Guy singer' },
        { word: 'Oprah Winfrey', hint: 'Talk show legend' },
        { word: 'Ellen DeGeneres', hint: 'Talk show host' },
        { word: 'Gordon Ramsay', hint: 'Angry chef' },
        { word: 'David Beckham', hint: 'Posh Spice husband' },
        { word: 'Virat Kohli', hint: 'Indian cricketer' },
        { word: 'Walt Disney', hint: 'Mickey Mouse creator' },
        { word: 'Elvis Presley', hint: 'King of Rock and Roll' },
        { word: 'Freddie Mercury', hint: 'Queen singer' },
        { word: 'David Bowie', hint: 'Ziggy Stardust' },
        { word: 'Prince', hint: 'Purple Rain' },
        { word: 'Madonna', hint: 'Queen of Pop' },
        { word: 'Britney Spears', hint: 'Toxic singer' },
        { word: 'Shakira', hint: 'Hips Don\'t Lie' },
        { word: 'Jennifer Lopez', hint: 'J.Lo' },
    ]
};

/**
 * UI Translation mapping for static UI elements.
 */
export const UI_TRANSLATIONS = {
    en: {
        citizen: 'CITIZEN',
        impostor: 'IMPOSTOR',
        secretWord: 'Secret Word',
        hint: 'Hint',
    },
    // Add other languages here if you want STATIC UI translation support
    // But dynamic content (words) will use the API.
};

/**
 * Get a random word and hint from specific categories or mixed.
 * @param {string|Array<string>} categoryKeys - The key(s) of the category.
 * @returns {Object} { word, hint }
 */

// Track recently used words to avoid immediate repeats
let recentlyUsedWords = [];
const MAX_RECENT_WORDS = 20; // Remember last 20 words

export function getRandomWord(categoryKeys = ['all']) {
    let availableWords = [];
    const keys = Array.isArray(categoryKeys) ? categoryKeys : [categoryKeys];

    // Helper to add category to word objects
    const addCategory = (list, cat) => list.map(w => ({ ...w, category: cat }));

    if (keys.includes('all') || keys.length === 0) {
        // When 'all' is selected, only include FREE/unlocked categories
        const freeCategories = CATEGORY_LABELS
            .filter(c => c.key !== 'all' && (c.free === true || (!c.premium && !c.free)))
            .flatMap(c => {
                // If category has subcategories, include them instead of parent
                if (c.subcategories) {
                    return c.subcategories.map(sub => sub.key);
                }
                return [c.key];
            });
        
        // Only add words from free categories
        freeCategories.forEach(key => {
            if (wordCategories[key]) {
                availableWords = [...availableWords, ...addCategory(wordCategories[key], key)];
            }
        });
    } else {
        // When specific categories are selected, use them directly
        // (assumes the UI already filtered out premium categories)
        keys.forEach(key => {
            if (key !== 'all' && wordCategories[key]) {
                availableWords = [...availableWords, ...addCategory(wordCategories[key], key)];
            }
        });
    }

    // Fallback - shouldn't happen if 'all' is always an option
    if (availableWords.length === 0) {
        availableWords = addCategory(wordCategories.food, 'food');
    }

    // Filter out recently used words if we have enough options
    let filteredWords = availableWords.filter(w => !recentlyUsedWords.includes(w.word));

    // If we've exhausted all words, reset the recent list
    if (filteredWords.length === 0) {
        recentlyUsedWords = [];
        filteredWords = availableWords;
    }

    // Pick random word from filtered list
    const randomIndex = Math.floor(Math.random() * filteredWords.length);
    const selectedWord = filteredWords[randomIndex];

    // Track this word as recently used
    recentlyUsedWords.push(selectedWord.word);
    if (recentlyUsedWords.length > MAX_RECENT_WORDS) {
        recentlyUsedWords.shift(); // Remove oldest
    }

    return selectedWord;
}

export const CATEGORY_LABELS = [
    { key: 'all', label: 'Random (All)' },
    { key: 'dailyLife', label: 'Daily Life', free: true },
    { key: 'things', label: 'Things', free: true },
    { key: 'movies', label: 'Movies', premium: true },
    { key: 'games', label: 'Games', premium: true },
    { key: 'places', label: 'Places', free: true },
    { key: 'food', label: 'Food', free: true },
    { key: 'objects', label: 'Objects', free: true },
    { key: 'trends', label: 'Trends', premium: true },
    { key: 'sport', label: 'Sports', premium: true },
    { key: 'science', label: 'Science', premium: true },
    { key: 'history', label: 'History', premium: true },
    { key: 'mythology', label: 'Myth', premium: true },
    { key: 'nature', label: 'Nature', premium: true },
    { key: 'tech', label: 'Tech', premium: true },
    { key: 'fashion', label: 'Fashion', premium: true },
    { key: 'genZ', label: 'Gen Z', premium: true },
    { key: 'ballKnowledge', label: 'Ball Knowledge', free: true, subcategories: [
        { key: 'football', label: 'Football' },
        { key: 'basketball', label: 'Basketball' },
    ]},
    { key: 'famousPeople', label: 'Famous People', premium: true },
];
